In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 3, 7], [5, 0, 2]])
print(A)
print(A.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [3]:
# 转置
print(A.T)
print(A.T.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [4]:
# 矩阵相加
print(A + B)

[[ 2  5 10]
 [ 9  5  8]]


In [5]:
# 矩阵与标量相乘
print(A * 3)

[[ 3  6  9]
 [12 15 18]]


In [6]:
# 矩阵与向量相乘
x = np.array([2, 3, 4])
print(A)
print(A * x)

[[1 2 3]
 [4 5 6]]
[[ 2  6 12]
 [ 8 15 24]]


In [7]:
# 矩阵与矩阵相乘 (对应元素相乘, 哈达玛积) 
print('A=\n',A)
print('B=\n',B)
print(A * B)

A=
 [[1 2 3]
 [4 5 6]]
B=
 [[1 3 7]
 [5 0 2]]
[[ 1  6 21]
 [20  0 12]]


In [8]:
# 矩阵乘法
# print(A.dot(B.T))
print(A @ B.T)

[[28 11]
 [61 32]]


In [9]:
# 求逆
C = np.array([[1,2],[3,5]])
C_inv = np.linalg.inv(C)
print('C 的逆:\n',C_inv)

C 的逆:
 [[-5.  2.]
 [ 3. -1.]]


In [10]:
print(C @ C_inv)

[[1.00000000e+00 2.22044605e-16]
 [4.44089210e-16 1.00000000e+00]]


In [11]:
A_inv = np.linalg.pinv(A)
print('A 的伪逆矩阵: \n',A_inv)

A 的伪逆矩阵: 
 [[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]


In [12]:
# 向量化
print(A.flatten())

[1 2 3 4 5 6]


In [13]:
# 矩阵内积
print('<A, B> = ',np.sum(A * B))

<A, B> =  60


In [14]:
print('<A, B> = ',np.dot(A.flatten(),B.flatten()))

<A, B> =  60


In [15]:
# 哈达玛积
print('哈达玛积: \n', A * B)

哈达玛积: 
 [[ 1  6 21]
 [20  0 12]]


In [16]:
print('哈达玛积: \n', np.multiply(A, B))

哈达玛积: 
 [[ 1  6 21]
 [20  0 12]]


In [17]:
# 克罗内克积
print('克罗内克积: \n', np.kron(A,B))

克罗内克积: 
 [[ 1  3  7  2  6 14  3  9 21]
 [ 5  0  2 10  0  4 15  0  6]
 [ 4 12 28  5 15 35  6 18 42]
 [20  0  8 25  0 10 30  0 12]]


In [18]:
# 定义张量
tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor)
print(tensor.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [20]:
# 计算梯度
f = np.array([1,2,4,7,11,16])
grad = np.gradient(f)
print(grad)

[1.  1.5 2.5 3.5 4.5 5. ]


In [23]:
print(B)
print(np.gradient(B))

[[1 3 7]
 [5 0 2]]
(array([[ 4., -3., -5.],
       [ 4., -3., -5.]]), array([[ 2. ,  3. ,  4. ],
       [-5. , -1.5,  2. ]]))


In [24]:
print(tensor)
print(np.gradient(tensor))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(array([[[6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.]]]), array([[[3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.]]]), array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]]))
