In [18]:
import numpy as np

In [19]:
# 定义向量
x = np.array([2, 6, 8])
print(x)
print(x.shape)

[2 6 8]
(3,)


In [20]:
# 向量转置
print(x.T)
print(x.shape)

[2 6 8]
(3,)


In [21]:
# 相加
y = np.array([1, 3, 7])
print(x + y)

[ 3  9 15]


In [22]:
# 向量与标量相乘
print(x * 3)

[ 6 18 24]


In [23]:
# 向量与向量相乘 (对应位置元素相乘)
print(x * y)

[ 2 18 56]


In [24]:
# 向量点乘
# np.dot(x, y)
# x @ y
print(x.dot(y))

76


In [25]:
# 计算范数
l0_norm = np.linalg.norm(x, ord=0)
print(l0_norm)
l1_norm = np.linalg.norm(x, ord=1)
print(l1_norm)
l2_norm = np.linalg.norm(x, ord=2)
print(l2_norm)

3.0
16.0
10.198039027185569
