In [1]:
import numpy as np

In [2]:
# 随机生成(0,1)均匀分布的数据
a = np.random.rand(5)
print(a)

[0.41717374 0.71350131 0.27138892 0.64116568 0.2550116 ]


In [3]:
a = np.random.rand(2,3)
print(a)

[[0.87647528 0.57889913 0.27015297]
 [0.34991634 0.07091126 0.0366525 ]]


In [6]:
# 随机生成均匀分布的整数
b = np.random.randint(0,100,size=(2,3))
print(b)

[[91 20 71]
 [94 42 63]]


In [8]:
# 随机生成服从标准正态分布的数据
c = np.random.randn(2,5)
print(c)

[[-1.10089754 -0.9186736  -0.35656778  0.19762878 -1.37424956]
 [ 0.4166747  -1.61686712 -0.09995712  0.63847837 -0.70618431]]


In [9]:
print((c+5)*10) # 扩大均值, 方差

[[38.99102461 40.81326398 46.43432222 51.97628778 36.25750444]
 [54.16674696 33.83132881 49.00042878 56.38478374 42.9381569 ]]
