In [35]:
from sklearn.preprocessing import MinMaxScaler

In [36]:
X = [[2, 1], [3, 1], [1, 4], [2, 6]]

In [37]:
# 定义归一化类的对象
scaler = MinMaxScaler(feature_range=(-1, 1))
# 将缩放器应用到特征上
X_scaled = scaler.fit_transform(X)
print(X_scaled)

[[ 0.  -1. ]
 [ 1.  -1. ]
 [-1.   0.2]
 [ 0.   1. ]]


In [38]:
from sklearn.preprocessing import StandardScaler

In [39]:
print(X)

[[2, 1], [3, 1], [1, 4], [2, 6]]


In [40]:
# 标准化
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled)

[[ 0.         -0.94280904]
 [ 1.41421356 -0.94280904]
 [-1.41421356  0.47140452]
 [ 0.          1.41421356]]


In [41]:
import numpy as np
X = np.array(X)
print(X)

[[2 1]
 [3 1]
 [1 4]
 [2 6]]


In [42]:
mean = np.mean(X, axis=0)
print(mean)  # 平均
std = np.std(X, axis=0)
print(std)  # 方差
# 手动标准化
print('标准化:\n',(X - mean) / (std))  # (X-平均)/方差

[2. 3.]
[0.70710678 2.12132034]
标准化:
 [[ 0.         -0.94280904]
 [ 1.41421356 -0.94280904]
 [-1.41421356  0.47140452]
 [ 0.          1.41421356]]
